home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
]

jogo_olimpicos/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('create_competition/', include('create_competition.urls')),
    path('register_result/', include('register_result.urls')),
    path('ranking/', include('ranking.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

jogos_olimpicos/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('create_competition/', include('create_competition.urls')),
    path('register_result/', include('register_result.urls')),
    path('ranking/', include('ranking.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ranking/urls.py
from django.urls import path

from . import views

app_name = 'ranking'

urlpatterns = [
    path('', views.ranking, name='home'),
    path('<int:id>', views.modality, name='modality')
]

home/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'home/pages/home.html')

ranking/views.py
from django.shortcuts import render


def ranking(request):
    return render(request, 'ranking/pages/home.html')


def modality(request, id):
    return render(request, 'ranking/pages/modality.html', context={
        'id': id
    })

ranking/templates/ranking/pages/home.html
{% extends 'global/pages/base.html' %}
{% load static %}

{% block title %}RANKING{% endblock title %}

{% block content %}
<header>
    <center><h1>RANKING</h1></center>
</header>
<div class="offset-1 col-10 list-div">
    <div class="row justify-content-md-center">
        <div class="col col-lg-2">
            <a href="{% url 'ranking:modality' 1 %}">
                <div class="row">
                    <img class="img-ranking" src="{% static 'ranking/imgs/img_100m_rasos.png' %}" alt="">
                </div>
                <div class="row">
                    <p>100m rasos</p>
                </div>
            </a>
        </div>
        <div class="col col-lg-2">
            <a href="{% url 'ranking:modality' 2 %}">
                <div class="row">
                    <img class="img-ranking" src="{% static 'ranking/imgs/img_lancamento_de_dardo.png' %}" alt="">
                </div>
                <div class="row">
                    <p>Lancamento de Dardo</p>
                </div>
            </a>
        </div>
    </div>
    <div class="col-9 search"></div>
</div>
{% endblock content %}

ranking/templates/ranking/pages/modality.html
{% extends 'global/pages/base.html' %}

{% block title %}MODALIDADE {{ id }}{% endblock title %}

{% block content %}
<header>
    <center><h1>MODALIDADE</h1></center>
</header>
<h3>{{ id }}</h3>
{% endblock content %}