create_competition/urls.py
from django.urls import path

from . import views

app_name = 'create_competition'

urlpatterns = [
    path('', views.create_competition, name='home'),
    path('created', views.created_competition, name='created'),
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
]

jogo_olimpicos/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('create_competition/', include('create_competition.urls')),
    path('register_result/', include('register_result.urls')),
    path('ranking/', include('ranking.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

jogos_olimpicos/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('create_competition/', include('create_competition.urls')),
    path('register_result/', include('register_result.urls')),
    path('ranking/', include('ranking.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

create_competition/models.py
from django.db import models


class Competition(models.Model):

    names_competition = (
        ('100m rasos', '100m rasos'),
        ('Lançamento de Dardo', 'Lançamento de Dardo')
    )
    competition = models.CharField(
        max_length=60,
        choices=names_competition
    )

    def __str__(self):
        return self.competition


class CreateCompetition(models.Model):

    name_athlete = models.CharField(max_length=255)
    weight_athlete = models.CharField(max_length=25)

    place_competition_op = (
        ('Acre', 'Acre'),
        ('Alagoas', 'Alagoas'),
        ('Amapá', 'Amapá'),
        ('Amazonas', 'Amazonas'),
        ('Bahia', 'Bahia'),
        ('Ceará', 'Ceará'),
        ('Distrito Federal', 'Distrito Federal'),
        ('Espírito Santo', 'Espírito Santo'),
        ('Goiás', 'Goiás'),
        ('Maranhão', 'Maranhão'),
        ('Mato Grosso', 'Mato Grosso'),
        ('Mato Grosso do Sul', 'Mato Grosso do Sul'),
        ('Minas Gerais', 'Minas Gerais'),
        ('Pará', 'Pará'),
        ('Paraíba', 'Paraíba'),
        ('Paraná', 'Paraná'),
        ('Pernambuco', 'Pernambuco'),
        ('Piauí', 'Piauí'),
        ('Rio de Janeiro', 'Rio de Janeiro'),
        ('Rio Grande do Norte', 'Rio Grande do Norte'),
        ('Rio Grande do Sul', 'Rio Grande do Sul'),
        ('Rondônia', 'Rondônia'),
        ('Roraima', 'Roraima'),
        ('Santa Catarina', 'Santa Catarina'),
        ('São Paulo', 'São Paulo'),
        ('Sergipe', 'Sergipe'),
        ('Tocantins', 'Tocantins')
    )

    age_athlete = models.CharField(max_length=25)
    height_athlete = models.CharField(max_length=25)
    name_competition = models.ForeignKey(
        Competition, on_delete=models.SET_NULL, null=True
    )
    place_competition = models.CharField(
        max_length=255,
        choices=place_competition_op
    )

    created_at = models.DateTimeField(auto_now_add=True)

    # updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name_athlete


class DatabaseCompetition(models.Model):

    id_athlete = models.ForeignKey(
        CreateCompetition, on_delete=models.SET_NULL, null=True
    )
    name_competition = models.ForeignKey(
        Competition, on_delete=models.SET_NULL, null=True
    )
    meters = models.FloatField()
    time = models.FloatField()

    def __str__(self):
        return self.id_athlete

create_competition/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import CreateCompetition


def add_attr(field, attr_name, attr_new_val):
    existing_attr = field.widget.attrs.get(attr_name, '')
    field.widget.attrs[attr_name] = f'{existing_attr} {attr_new_val}'.strip()


def add_placeholder(field, placeholder_val):
    add_attr(field, 'placeholder', placeholder_val)


def check_age(age_athlete):
    if int(age_athlete) < 15:
        raise ValidationError((
            'Para participar, você precisa ter 15 anos ou mais.'
        ))
    elif int(age_athlete) > 80:
        raise ValidationError((
            'A idade máxima permitida é 80 anos.'
        ))


def check_height(height_athlete):
    if float(height_athlete) <= 1:
        raise ValidationError((
            'Para participar, você precisa ter mais de 1 metro de altura.'
        ))


class CreateForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        add_placeholder(self.fields['name_athlete'], 'Digite o seu nome')
        add_placeholder(self.fields['age_athlete'], 'Digite a sua idade')
        add_placeholder(self.fields['height_athlete'], 'Digite a sua altura')
        add_placeholder(self.fields['weight_athlete'], 'Digite o seu peso')
        add_attr(self.fields['name_athlete'], 'class', 'form-control')
        add_attr(self.fields['age_athlete'], 'class', 'form-control')
        add_attr(self.fields['height_athlete'], 'class', 'form-control')
        add_attr(self.fields['weight_athlete'], 'class', 'form-control')
        add_attr(self.fields['name_competition'], 'class',
                 'form-control custom-select selectpicker')
        add_attr(self.fields['place_competition'], 'class',
                 'form-control custom-select selectpicker')

    name_athlete = forms.CharField(
        required=True,
        label='Nome:'
    )
    age_athlete = forms.CharField(
        required=True,
        label='Idade:',
        error_messages={
            'required': 'Digite uma idade válida.'
        },
        widget=forms.TextInput(attrs={
            'type': 'number'
        }),
        validators=[check_age]
    )
    height_athlete = forms.CharField(
        required=True,
        label='Altura:',
        error_messages={
            'required':  'Digite uma altura válida.'
        },
        widget=forms.TextInput(attrs={
            'type': 'number',
            'step': '0.01'
        }),
        validators=[check_height]
    )
    weight_athlete = forms.CharField(
        required=True,
        label='Peso:',
        error_messages={
            'required':  'Digite um peso válido.'
        },
        widget=forms.TextInput(attrs={
            'type': 'number',
            'step': '0.01'
        })
    )

    class Meta:
        model = CreateCompetition
        fields = '__all__'

        labels = {
            'name_competition': 'Modalidade:',
            'place_competition': 'Local:'
        }

        help_texts = {
            'name_competition': 'Escolha a sua modalidade.'
        }

        error_messages = {
            'name_competition': {
                'required':  'Escolha uma modalidade.'
            }
        }

    # def clean_name_athlete(self):
    #     data = self.cleaned_data.get('name_athlete')

    #     if 'Hygor' in data:
    #         raise ValidationError(
    #             'Não digite %(value)s no campo Nome',
    #             code='invalid',
    #             params={'value': '"Hygor"'}
    #         )

    #     return data

    def clean(self):
        cleaned_data = super().clean()
        name_athlete = cleaned_data.get('name_athlete')

        if 'Hygor' in name_athlete:
            raise ValidationError({
                'name_athlete': ValidationError(
                    'Não digite %(value)s no campo Nome',
                    code='invalid',
                    params={'value': '"Hygor"'}
                )
            })

create_competition/views.py
from django.contrib import messages
from django.http import Http404
from django.shortcuts import redirect, render

from .forms import CreateForm
from .models import CreateCompetition


def create_competition(request):
    create_form_data = request.session.get('create_form_data', None)
    form = CreateForm(create_form_data)
    name_athlete = form['name_athlete']
    print(f'FORM: {name_athlete}')

    getAthletes = CreateCompetition.objects.filter().order_by('-id')

    return render(request, 'create_competition/pages/home.html',
                  context={
                      'if_competition_ok': True,
                      'athletes': getAthletes,
                      'form': form
                  })


def created_competition(request):
    if not request.POST:
        raise Http404()

    POST = request.POST
    # Criando session
    request.session['create_form_data'] = POST
    form = CreateForm(POST)

    if form.is_valid():
        data = form.save()  # noqa: F841
        messages.success(request, 'Cadastro realizado com sucesso!')

        del(request.session['create_form_data'])

    return redirect('create_competition:home')

home/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'home/pages/home.html')

create_competition/templates/create_competition/pages/home.html
{% extends 'global/pages/base.html' %}

{% block title %}CRIAR COMPETIÇÃO{% endblock title %}

{% block content %}
<center><h1>CRIAR COMPETIÇÃO</h1></center>
{% include 'global/partials/messages.html' %}
<p>Criar uma competição [nome, local e data/hora da disputa], já informando os atletas participantes [nome, idade, altura e peso]</p>
{% if if_competition_ok is not True %}
<header>
    <div class="container">
        <div class="row">
            <div class="col-12 status-competition-off">Cadastro finalizado.</div>
        </div>
    </div>
</header>
{% else %}
<br>
<form method="POST" action="{% url 'create_competition:created' %}">
    {% csrf_token %}
    {% comment %} {{ form.as_p }} {% endcomment %}
    <div class="row">
        {% for field in form %}
        <div class="col-md-6">
            <div class="mb-2 row">
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {{ field }}
                {% if field.help_text %}
                    <p>{{ field.help_text }}</p>
                {% endif %}
                {{ field.errors }}
            </div>
        </div>
        {% endfor %}
    </div>
    <br>
    <div class="container list-div">
        <ul class="list-athlete">
            <li class="item-athlete">
                <div class="row">
                    <div class="col">NOME</div>
                    <div class="col">MODALIDADE</div>
                    <div class="col">LOCAL</div>
                    <div class="col">DATA</div>
                    {% comment %} <div class="col">AÇÃO</div> {% endcomment %}
                </div>
            </li>
            {% for i in athletes %}
            <li class="item-athlete">
                <div class="row">
                    <div class="col">{{i.name_athlete}}</div>
                    <div class="col">{{i.name_competition}}</div>
                    <div class="col">{{i.place_competition}}</div>
                    <div class="col">----</div>
                </div>
            </li>
            {% endfor %}
            <span>Objetos recuperados do views.py: </span>{{ athletes }}
        </ul>
    </div>
    <br>
    <div class="container">
        <div class="row">
            <input type="submit" class="col-12 add-athlete" value="Adicionar Atleta">
        </div>
    </div>
    {{ field.errors }}
</form>
{% endif %}
<br>
<br>
{% endblock content %}